BrightspaceHypermediaComponents/enrollments

- components/d2l-enrollment-card/d2l-enrollment-card.html
This was set in `d2l-course-image-tile` on the `d2l-image-tile`, but I forgot to move it over. Only affects long, non-breaking course names.
> Fix long course names

- bower.json
- components/d2l-enrollment-card/d2l-enrollment-card.html
- test/d2l-enrollment-card/d2l-enrollment-card.js
The `d2l-organization-info` component now supports showing additional information for future/past/inactive courses, so the image overlay is being retired. Unfortunately, there is still some remaining date-related code here, to allow us to set the `past-course` attribute on the card, as well as greying out inaccessible courses. There is probably a better way to do this, but the implementation of this behaviour in `d2l-organization-info` isn't quite complete yet anyway - we are still missing the status badge, which will slightly modify the available information.
Requires https://github.com/BrightspaceHypermediaComponents/organizations/pull/5, and a `bower.json` update once that has been released.
> US97555 Remove image overlay

- bower.json
This includes the change to add a `name="content"` to the content slot of `d2l-card`, which we now use here in `d2l-enrollment-card`.
> Bump d2l-tile

- components/d2l-user-activity-usage/d2l-user-activity-usage.html
- test/d2l-user-activity-usage/d2l-user-activity-usage.js
When a due date is set to `tomorrow + 1 year` then it would show as `due tomorrow`. Now it shows the correct date.
> Relative dates check year when deciding to be shown.

- components/d2l-enrollment-card/d2l-enrollment-card.html
Note this one was built off of https://github.com/BrightspaceHypermediaComponents/enrollments/pull/15
>  Temporary fix to keep title text aligned with[out] badge.

- bower.json
- components/d2l-enrollment-card/d2l-enrollment-card.html
* the new version of `d2l-card` includes the y-translation and box-shadow on hover
> Update to use normal card.

- bower.json
- components/d2l-enrollment-card/d2l-enrollment-card.html
- test/d2l-enrollment-card/d2l-enrollment-card.js
- wct.conf.json
Enrollment cards wouldn't reset their state. So if the sort order changed, the card would get a new `href` but all the badges would stay. So new course information but with old inactive badge
> Resets the state if the enrollment changes.

- components/d2l-enrollment-card/d2l-enrollment-card.html
- components/d2l-user-activity-usage/d2l-user-activity-usage.html
So when changing the sort order of cards the `href` would be updated for a card. But some of the information from the old `href` would remain or hide the new information. Here is hopefully all the resetting required.
> Cards properly reset.

- components/d2l-enrollment-card/lang/ar.json
- components/d2l-enrollment-card/lang/de.json
- components/d2l-enrollment-card/lang/es.json
- components/d2l-enrollment-card/lang/fi.json
- components/d2l-enrollment-card/lang/fr.json
- components/d2l-enrollment-card/lang/ja.json
- components/d2l-enrollment-card/lang/ko.json
- components/d2l-enrollment-card/lang/nl.json
- components/d2l-enrollment-card/lang/pt.json
- components/d2l-enrollment-card/lang/sv.json
- components/d2l-enrollment-card/lang/tr.json
- components/d2l-enrollment-card/lang/zh-tw.json
- components/d2l-enrollment-card/lang/zh.json
The status indicator for a course being complete uses the term 'Completed' in my courses, and it should be 'Complete' to be consistent.
> Completed to Complete.

- components/d2l-enrollment-card/d2l-enrollment-card.js
I think the callback chain is a bug since `performSirenAction` only returns single `enrollment`, at the same time, I don't see any misbehavior caused by this issue, so I'm not sure if we need this fix. I tested the fix, I observed the same with and without the change when pinning.
> DE34146-fix crazy callback chains

- components/d2l-enrollment-summary-view/d2l-enrollment-summary-view.js
- test/d2l-enrollment-summary-view/d2l-enrollment-summary-view.html
- test/d2l-enrollment-summary-view/d2l-enrollment-summary-view.js
- test/index.html
Basically this makes it smarter about which courses it adds to the list. Don't re-add course and remove courses that no longer exist.
I am tracking courses by index in a separate object. So I can easily maintain the display array.
Only arrays can be loop through. So that is why we have the second flattened array.
> Stop duplications

- components/d2l-enrollment-hero-banner/d2l-enrollment-hero-banner.js
- test/d2l-enrollment-hero-banner/d2l-enrollment-hero-banner.js
- test/index.html
This pull request adds a context menu to the hero banner to match the `d2l-enrollment-card` context menu.
1. Wrapped the component in a `div` with the `d2l-visible-on-ancestor-target` class to allow the context menu to be shown on hover.
2. Added a `d2l-dropdown-more` and `d2l-dropdown-menu` with the following items:
- Course Offering Information
- Change Image
- Pin / Unpin
3. Changed `token$=` to `token=` to avoid the token being interpreted as a string instead of a function causing a JS error and preventing the hero banner image from loading.
> Add context menu to hero banner

- components/d2l-enrollment-summary-view/d2l-enrollment-summary-view.js
- demo/d2l-enrollment-summary-view/d2l-enrollment-summary-view-demo.html
- package.json
1. This pull request adds stickiness to the `d2l-enrollment-summary-view`'s progress bar so that the progress bar stays pinned at the top of the page when scrolling past it.
1. Add a dependency on `lie` to resolve the missing import error during CI runs due to `lie` no longer being brought in implicitly as a sub-dependency.
> Add stickiness to the enrollment summary view progress bar

- components/d2l-enrollment-detail-card/d2l-enrollment-detail-card.js
- demo/d2l-enrollment-detail-card/d2l-enrollment-detail-card-demo.html
This pull request updates the `d2l-enrollment-detail-card` to show pulse every 1.8 seconds instead of shimmering. The animation now also applies to the text placeholders instead of just the image placeholder.
> Change the d2l-enrollment-detail-card skeleton to use a pulse animation

- components/d2l-enrollment-hero-banner/d2l-enrollment-hero-banner.js
This pull request updates the `d2l-enrollment-hero-banner` to show pulse every 1.8 seconds during loading instead of shimmering. The animation now also applies to the text placeholders instead of just the image placeholder.
> Change the d2l-enrollment-hero-banner skeleton to use a pulse animation

- components/d2l-enrollment-summary-view/d2l-enrollment-summary-view.js
> Add skeleton loader for the d2l-enrolllment-summary-view to hide the header, side-bar, and detail-cards while loading.

- components/d2l-enrollment-summary-view/d2l-enrollment-summary-view-layout.js
- components/d2l-enrollment-summary-view/d2l-enrollment-summary-view.js
- Updated the position of the summary to match nav
- Module text beside continue wraps better.
> Summary View layout and text wrapping

- components/build/lang/en.js
- components/d2l-enrollment-hero-banner/d2l-enrollment-hero-banner.js
- components/lang/en.json
- demo/d2l-enrollment-hero-banner/d2l-enrollment-hero-banner-demo.html
- package.json
- test/d2l-enrollment-hero-banner/d2l-enrollment-hero-banner.js
1. Add a progress meter to the `d2l-enrollment-hero-banner` to report the number of completed modules for the enrollment.
2. Add a dependency on `@brightspace-ui/core` for the meter component.
3. Add two test cases to ensure completion is calculated correctly for both learning paths and course offerings.
> Add a d2l-enrollment-hero-banner progress meter

- components/d2l-enrollment-summary-view/d2l-enrollment-summary-view.js
- test/d2l-enrollment-summary-view/d2l-enrollment-summary-view.html
- test/d2l-enrollment-summary-view/d2l-enrollment-summary-view.js
1. This pull request adds loading states so that the header text, body text, and body images are loaded as a chunk when all of their sub-pieces have loaded.
1. Force loading has been adding so that sub-pieces will be revealed after 2 seconds even if all sub-pieces in the chunk they belong to haven't been loaded.
> Add loading states to load the body texts, body images, and header chunks

- components/d2l-enrollment-summary-view/d2l-enrollment-summary-view-layout.js
- components/d2l-enrollment-summary-view/d2l-enrollment-summary-view-meter.js
- components/d2l-enrollment-summary-view/d2l-enrollment-summary-view-tag-list.js
- components/d2l-enrollment-summary-view/d2l-enrollment-summary-view.js
1. The layout column padding should be on the inside in the `d2l-enrollment-summary-view-layout`
1. The border on the `d2l-enrollment-summary-view-layout` should be on the left instead of the right
1. The `d2l-enrollment-summary-view` button should have its margin on the opposite side
1. The `d2l-enrollment-summary-view` continue label margin should be on the opposite side
1. The `d2l-enrollment-summary-view-meter` should progress in the correct direction
> Add RTL fixes for the d2l-enollment-summary-view and associated sub-components

- components/d2l-enrollment-collection-widget/d2l-enrollment-collection-widget.js
- demo/data/base/enrollmentCollection.json
Refactor to use grids instead of a flex. This will make each card have equal space. Still looks and acts the same.
> Use grids instead of flex for the my learning

- components/build/lang/en.js
- components/d2l-enrollment-hero-banner/d2l-enrollment-hero-banner.js
- components/lang/en.json
- test/d2l-enrollment-hero-banner/d2l-enrollment-hero-banner.js
This pull request updates the hero card to show activity completions for paths instead of module completions. Module completions will still be shown if a course is displayed within the hero card.
> Add activity completion in the Hero card

- components/d2l-enrollment-summary-view/d2l-enrollment-summary-view.js
1. Add a top border to the header title bar for separation
2. Centre the title and tag list vertically within the header
> Update the enrollment summary view header styling to fit with hidden nav links

- components/d2l-enrollment-hero-banner/d2l-enrollment-hero-banner.js
- demo/data/enrollments/long-name/organizations/2.json
- The css for the hero banner title will now prevent the title from overflowing its container. The container will be the normal height for one or two lines. If the title is greater than two lines, the banner will now wrap the text and expand vertically to fit the title.
- The banner title and content elements are now children of the white box they display in.
Before:
After:
Excessively long words:
> DE35575 - Hero Banner title will not overflow white box.

- components/d2l-enrollment-summary-view/d2l-enrollment-summary-view.js
If the text extends further than one line, it will no longer wrap and increase the height of the progress bar and continue button. Instead, it will now be truncated by an ellipsis.
> The module name text next to the Continue button is now limited to one line.

- test/d2l-enrollment-hero-banner/d2l-enrollment-hero-banner.js
- Update the pinning tests to not depend on `d2l-menu-item-last` due to it being an internal implementation detail that caused the tests to break.
> Fix Pinning Tests

- components/d2l-enrollment-summary-view/d2l-enrollment-summary-view.js
Currently, there is no method to get the total module count from the siren-sdk. Consequently, there's no known time at which we can say all modules have loaded.
The existing solution is to wait 200ms after the first module loads to set the loaded flag to true, and fire the event to show the completion button and text. However, if there are no modules to load, this will never fire and the system will remain in a perpetual loading state.
This has been worked around by introducing a backup delay of 800ms that ensures the show completion continue event will still fire in a reasonable amount of time if no modules are loaded,
with 800ms being enough time for an appropriate module to likely have been found and loaded already, while still being fast enough to meet user expectations.
Before: …
> Enrollment Summary's loaded event will now fire even if no modules exist.

- components/d2l-enrollment-hero-banner/d2l-enrollment-hero-banner.js
Skeleton loader placeholders for completion status, duration in the hero banner no longer appear post-load.
The pulsing placeholder elements have been removed but the divs remain to ensure proper spacing via `dehb-tag-placeholder`.
> Removed skeleton loader placeholders from hero banner

- components/d2l-enrollment-collection-widget/d2l-enrollment-collection-widget.js
- components/d2l-enrollment-hero-banner/d2l-enrollment-hero-banner.js
- Define the number of columns based on the container width and a column width of 350 px to match My Courses. This was done with `offsetWidth` instead of media queries because different homepage widget layouts result in My Learning having different widths relative to the page size.
- Conditionally show the hero banner based on the number of columns and the number of enrollments.
> US112310: Make the My Learning widget responsive

- components/d2l-enrollment-collection-widget/d2l-enrollment-collection-widget.js
[DE37466](https://rally1.rallydev.com/#/detail/defect/362140783532?fdp=true)
Spacing issue when using keyboard navigation was due to margins being applied to the button instead of the anchor that wraps the button.
> Fixed spacing/transparency issue with View All Learning button

- components/d2l-enrollment-collection-widget/d2l-enrollment-collection-widget.js
[DE37432](https://rally1.rallydev.com/#/detail/defect/361871963468?fdp=true)
Edge cards now display correctly with grids. Issue was due to contentRect.width returning a pixel value (for only Edge, because Edge) instead of a pure number. Simply converting to a number solved the issue.
> Fixed Edge cards showing up as full width

- components/d2l-enrollment-collection-widget/d2l-enrollment-collection-widget.js
[DE37466](https://rally1.rallydev.com/#/detail/defect/362140783532?fdp=true)
Spacing issue still existed for the My Learning Widget -> View All Learning button, as the problem is that the anchor tag was tabbable. The anchor tag is no longer tabbable, only the button itself is.
> MLW view all anchor untabbable to prevent weird spacing

- components/d2l-enrollment-collection-view/d2l-enrollment-collection-view.js
- components/d2l-enrollment-detail-card/d2l-enrollment-detail-card.js
- test/d2l-enrollment-card/d2l-enrollment-card.js
[DE37652](https://rally1.rallydev.com/#/detail/defect/365729624044?fdp=true)
Ensures an activity title does not appear blue (clickable) on the View Learning Path page if it is inactive.
**Quality**
Tested with demo pages and local BSI
> Disabling link if course is inactive

- components/d2l-enrollment-summary-view/d2l-enrollment-summary-view.js
Continue button now describes what is going on when using a screen reader.
> Fix continue button label.

- components/d2l-enrollment-summary-view/d2l-enrollment-summary-view.js
[DE38478](https://rally1.rallydev.com/#/detail/defect/379552725536?fdp=true)
Incorporated d2l-button, because it seems like there's a lot of css work being done to achieve the same result, which is unnecessary.
before:
after:
> incorporate d2l-button

- components/d2l-enrollment-summary-view/d2l-enrollment-summary-view.js
[DE37664](https://rally1.rallydev.com/#/detail/defect/366057075248?fdp=true)
Basically, I can't seem to find an ideal solution for this. I don't think there is one. We just have to agree on a solution rather than none at all. I'll list the two other solutions below and why it's not a ideal:
1. using `aria-flowto`, limited support in browsers, doesn't work on voiceover, might confuse readers
2. changing html markup to make them seem like the title and description are next to each other. (we tried, its impossible given page design)
**Update**: decided to use offscreen component as it best matches our use-case
Quality
Tested with demo pages and local BSI
> added an off-screen component for description

- components/d2l-enrollment-summary-view/d2l-enrollment-summary-view.js
Fixes: [DE38478](https://rally1.rallydev.com/#/detail/defect/379552725536?fdp=true)
Bringing it back to the old link style buttons unfortunately, due to our inability for us to adapt d2l-button for our use-case. This is the same exact code that was there previously, it's just a revert commit.
Quality
Tested with demo pages with VoiceOver on Chrome and local BSI.
> Reverting the d2l-button incorporation

- components/d2l-enrollment-card/d2l-enrollment-card.js
- test/d2l-enrollment-card/d2l-enrollment-card.js
Add `focusDropdownOpener` function for my-courses to use after interacting with the image selector.  Similar to the `refreshImage` function, it first checks that the org you requested matches.  This will be used to fix a bunch of current focus issues in the `my-courses` widget.
> US115271 - Add focusDropdownOpener to enrollment card

- components/d2l-enrollment-card/d2l-enrollment-card.js
- components/d2l-enrollment-hero-banner/d2l-enrollment-hero-banner.js
- test/d2l-enrollment-card/d2l-enrollment-card.js
- test/d2l-enrollment-hero-banner/d2l-enrollment-hero-banner.js
Related to BrightspaceHypermediaComponents/siren-sdk#184, I'm migrating usages of the `processedDate` function from `OrganizationEntity` to no longer access `beforeStartDate` and `afterEndDate` directly, and to instead use the new functions.
In this case, the `d2l-enrollment-card` and `d2l-enrollment-hero-banner` were not getting the closed badge applied if `hideCourseEndDate` was true, even though that setting should only affect the date text displayed.  Using the new functions fixes that.  The logic between the two is exactly the same, as are the tests.
> DE38903 - Fix closed badge

- README.md
- components/d2l-enrollment-collection-view/d2l-enrollment-collection-view.js
- components/d2l-enrollment-collection-view/localization.js
- demo/d2l-enrollment-card/d2l-enrollment-card-demo.html
- demo/d2l-user-activity-usage/d2l-user-activity-usage-demo.html
- package.json
closes https://rally1.rallydev.com/#/detail/defect/405077696728?fdp=true
Defect caused by a switch to `rollup` in BSI builds
- Changed so that localization imports are explicit
- Installed `es-dev-server` because we should start moving away from `polymer-cli`
- This will start a dev server and auto-watch files on `npm start`, just like core
- Tested that all of the demo pages work. Performed some light maintenance on them
- Tested that My Learning page works in Legacy Edge with local LMS
> fix: Localization is broken for enrollment collection in 20.20.8 for Edge

- components/d2l-enrollment-card/d2l-enrollment-card.js
- test/d2l-enrollment-card/d2l-enrollment-card.js
Related to https://github.com/BrightspaceHypermediaComponents/organizations/pull/214, the same issue was happening for the aggregated a11y description higher up in the card.
> DE40642 - Fix a11y description on the enrollment card if the org changes
