BrightspaceHypermediaComponents/enrollments

- bower.json
- components/d2l-enrollment-card/d2l-enrollment-card.html
- test/d2l-enrollment-card/d2l-enrollment-card.js
Not a spectacular improvement, but part of the change to break apart the course tile. This component is an entity-driven component, and takes the organization/presentation hrefs.
> US97555 Use d2l-organization-info component

- components/d2l-user-activity-usage/d2l-user-activity-usage.html
- demo/data/enrollments/badges/userActivityUsage/3.json
- demo/data/enrollments/relative-dates/userActivityUsage/4.json
- demo/data/enrollments/relative-dates/userActivityUsage/5.json
- test/d2l-user-activity-usage/d2l-user-activity-usage.js
Modified demo and test to use the new api.
> Modified the user activity api parsing to read completion date.

- components/d2l-enrollment-card/d2l-enrollment-card.html
- components/d2l-user-activity-usage/d2l-user-activity-usage.html
- demo/d2l-enrollment-card/d2l-enrollment-card-demo.html
- demo/data/base/userActivityUsage.json
- demo/data/enrollments/badges/userActivityUsage/3.json
- demo/data/enrollments/new-enrollment/1.json
- demo/data/enrollments/new-enrollment/2.json
- demo/data/enrollments/new-enrollment/3.json
- demo/data/enrollments/new-enrollment/userActivityUsage/1.json
- demo/data/enrollments/new-enrollment/userActivityUsage/2.json
- demo/data/enrollments/relative-dates/userActivityUsage/1.json
- demo/data/enrollments/relative-dates/userActivityUsage/2.json
- demo/data/enrollments/relative-dates/userActivityUsage/3.json
- demo/data/enrollments/relative-dates/userActivityUsage/4.json
- demo/data/enrollments/relative-dates/userActivityUsage/5.json
- demo/data/enrollments/relative-dates/userActivityUsage/6.json
- demo/data/enrollments/relative-dates/userActivityUsage/7.json
- test/d2l-enrollment-card/d2l-enrollment-card.js
- test/d2l-user-activity-usage/d2l-user-activity-usage.js
Adds a blue indicator at the top of the card to show that this enrollment has not been accessed.
> New Course Highlight

- bower.json
- components/d2l-enrollment-card/d2l-enrollment-card.html
- components/d2l-enrollment-card/d2l-enrollment-updates.html
- demo/d2l-enrollment-card/d2l-enrollment-card-demo.html
- demo/data/base/organization.json
- demo/data/enrollments/update/notification/3.json
Requires:
https://github.com/BrightspaceHypermediaComponents/organizations/pull/15
> us97571 - disaggregate course updates

- components/d2l-user-activity-usage/d2l-user-activity-usage.html
> Completion badge shows when completed today.

- components/d2l-enrollment-card/d2l-enrollment-card.html
- test/d2l-enrollment-card/d2l-enrollment-card.js
My Courses - Generic naming of Badge CSS class can result in CSS clashes with custom widget content
> Made the css shady friendly.

- bower.json
- components/d2l-enrollment-card/d2l-enrollment-updates.html
> Tookout width:fit-content - doesn't work on IE11 and Edge

- components/d2l-enrollment-card/lang/en.json
Some how when I changed `Completed` to `Complete` I did change the english file.
> Completed to Complete

- components/d2l-enrollment-card/build/lang/en.html
- components/d2l-enrollment-card/build/lang/es.html
- components/d2l-enrollment-card/build/lang/fi.html
- components/d2l-enrollment-card/build/lang/ko.html
- components/d2l-enrollment-card/build/lang/nl.html
- components/d2l-enrollment-card/build/lang/sv.html
- components/d2l-enrollment-card/build/lang/tr.html
- components/d2l-enrollment-card/build/lang/zh-tw.html
- components/d2l-enrollment-card/build/lang/zh.html
- package.json
Some languages completed == complete
> Updated the terms.

- components/d2l-enrollment-detail-card/d2l-enrollment-detail-card.js
- demo/d2l-enrollment-detail-card/d2l-enrollment-detail-card-demo.html
- demo/index.html
- package.json
- test/d2l-enrollment-detail-card/d2l-enrollment-detail-card.html
- test/d2l-enrollment-detail-card/d2l-enrollment-detail-card.js
- test/index.html
The name is still to be decided as it might not be a card.
> Basic setup for new component d2l-enrollment-detail-card

- components/d2l-enrollment-detail-card/d2l-enrollment-detail-card.js
- demo/d2l-enrollment-detail-card/d2l-enrollment-detail-card-demo.html
Mocked up a skeleton as shown above.
> Detail Card Spacing

- components/d2l-enrollment-detail-card/d2l-enrollment-detail-card.js
- demo/d2l-enrollment-detail-card/d2l-enrollment-detail-card-demo.html
- demo/data/base/organization.json
- package.json
- test/d2l-enrollment-detail-card/d2l-enrollment-detail-card.html
- test/d2l-enrollment-detail-card/d2l-enrollment-detail-card.js
skeleton can turn on and off.
Adding description clamping in a later story.
> Added mock  data through api

- components/d2l-enrollment-detail-card/d2l-enrollment-detail-card.js
- package.json
- test/d2l-enrollment-detail-card/d2l-enrollment-detail-card.html
- test/d2l-enrollment-detail-card/d2l-enrollment-detail-card.js
Using the new d2l-organization-image.
> Using the new entity store

- components/d2l-enrollment-detail-card/d2l-enrollment-detail-card.js
- demo/d2l-enrollment-detail-card/d2l-enrollment-detail-card-demo.html
- demo/data/base/module1.json
- demo/data/base/module2.json
- demo/data/base/module3.json
- demo/data/base/organization.json
- demo/data/base/top-level-activity-sequence.json
- package.json
> Add list module to end of card

- components/d2l-enrollment-detail-card/d2l-enrollment-detail-card.js
- components/d2l-enrollment-summary-view/d2l-enrollment-summary-view-layout.js
- components/d2l-enrollment-summary-view/d2l-enrollment-summary-view-tag-list.js
- components/d2l-enrollment-summary-view/d2l-enrollment-summary-view.js
- demo/d2l-enrollment-summary-view/d2l-enrollment-summary-view-demo.html
- demo/data/base/enrollment.json
- demo/data/base/organization.json
- demo/data/enrollments/badges/1.json
- demo/data/enrollments/long-name/1.json
- demo/data/enrollments/new-enrollment/1.json
> Added d2l summary view with demos

- components/d2l-enrollment-detail-card/d2l-enrollment-detail-card.js
- components/d2l-enrollment-summary-view/d2l-enrollment-summary-view.js
- demo/d2l-enrollment-summary-view/d2l-enrollment-summary-view-demo.html
- package.json
> Summary view / detial card responsive

- components/d2l-enrollment-detail-card/d2l-enrollment-detail-card.js
- components/d2l-enrollment-summary-view/d2l-enrollment-summary-view-layout.js
> Focus and hover

- EnrollmentEntity.js
- package.json
> Enrollment Entity

- EnrollmentEntity.js
- components/d2l-enrollment-hero-banner/d2l-enrollment-hero-banner.js
- demo/d2l-enrollment-hero-banner/d2l-enrollment-hero-banner-demo.html
- demo/data/base/image.json
- demo/data/base/notification.json
- demo/data/enrollments/long-name/2.json
- demo/data/enrollments/long-name/organizations/2.json
- test/d2l-enrollment-hero-banner/d2l-enrollment-hero-banner.html
- test/d2l-enrollment-hero-banner/d2l-enrollment-hero-banner.js
> Hero Banner

- .travis.yml
- components/d2l-enrollment-hero-banner/d2l-enrollment-hero-banner.js
- demo/d2l-enrollment-hero-banner/d2l-enrollment-hero-banner-demo.html
Make the hero banner act the same as `d2l-card` (subtle) when hover, focus and click actions.
> Focus, hover and link

- EnrollmentCollectionEntity.js
- components/d2l-enrollment-card/d2l-enrollment-card.js
- components/d2l-enrollment-collection-widget/d2l-enrollment-collection-widget.js
- demo/d2l-enrollment-collection-widget/d2l-enrollment-collection-widget-demo.html
- demo/data/base/enrollmentCollection.json
- demo/data/base/semester.json
- demo/data/base/top-level-activity-sequence.json
- demo/data/base/userActivityUsage.json
Demo for enrollment collection widget
fixed self reference to demo data
fixed enrollment card notifications
> Enrollment collection widget skeleton

- components/d2l-enrollment-collection-widget/d2l-enrollment-collection-widget.js
- demo/d2l-enrollment-collection-widget/d2l-enrollment-collection-widget-demo.html
- demo/data/base/enrollmentCollection1.json
- demo/data/base/enrollmentCollection2.json
- demo/data/base/enrollmentCollection3.json
When there is two this is how they should look.
> 2 enrollment view.

- components/d2l-enrollment-card/d2l-enrollment-card.js
Thanks Stacey replacing the other places too
> US107197-use this.href everywhere

- components/d2l-enrollment-summary-view/d2l-enrollment-summary-view.js
- demo/d2l-enrollment-summary-view/d2l-enrollment-summary-view-demo.html
- demo/data/base/learning-path-sequence-root.json
- demo/data/base/learning-path.json
- demo/data/base/organization-learning-path.json
Using HM response from sequence to get content for the enrollment.
Requires:
https://github.com/BrightspaceHypermediaComponents/siren-sdk/pull/19
> using sequences to get courses for summary view

- components/d2l-enrollment-summary-view/d2l-enrollment-summary-view.js
> Dom repeat needs to use _orgHrefs

- components/d2l-enrollment-summary-view/d2l-enrollment-summary-view-layout.js
- components/d2l-enrollment-summary-view/d2l-enrollment-summary-view.js
- demo/data/base/organization-learning-path.json
- demo/data/base/organization.json
Screen shot from LE using local BSI branch.
To match:
> Adjust padding to fit designs in LE

- components/d2l-enrollment-card/d2l-enrollment-card.js
Should be merged after https://github.com/Brightspace/d2l-my-courses-ui/pull/757.
> Fire event with EnrollmentEntity instead of EnrollmentEntity._entity

- components/build/lang/en.js
- components/d2l-enrollment-summary-view/d2l-enrollment-summary-view-meter.js
- components/d2l-enrollment-summary-view/d2l-enrollment-summary-view.js
- components/lang/en.json
Woot.
Aria supported: "Completed {percentage}% of {title}"
> Progress Bar for summary component

- components/d2l-enrollment-summary-view/d2l-enrollment-summary-view.js
Well, the thing that wouldn't hurt anything turned into a defect :( I put it in the wrong place.
> Fix the continue button.

- components/d2l-enrollment-summary-view/d2l-enrollment-summary-view-meter.js
> Fill bar in IE11

- components/d2l-enrollment-hero-banner/d2l-enrollment-hero-banner.js
- test/d2l-enrollment-hero-banner/d2l-enrollment-hero-banner.js
[DE34588](https://rally1.rallydev.com/#/39602890252d/detail/defect/325235872004)
Adding organization title and code to the hero banner link for accessibility.
Tested locally.
> adding accessibility data to hero banner link

- components/build/lang/en.js
- components/d2l-enrollment-collection-widget/d2l-enrollment-collection-widget.js
- demo/d2l-enrollment-collection-widget/d2l-enrollment-collection-widget-demo.html
- demo/data/base/enrollmentCollection4.json
- package.json
When the My Learning widget has no content to display, it will now display an alert informing the user that there is no content to display, similarly to My Courses.
> My Learning widget shows an empty state if no enrollments exist

- components/d2l-enrollment-collection-view/d2l-enrollment-collection-view.js
- demo/d2l-enrollment-collection-view/d2l-enrollment-collection-view.html
- package.json
Initial commit of `d2l-enrollment-collection-view` webcomponent.
> Added d2l-enrollment-collection-view

- components/d2l-enrollment-collection-widget/d2l-enrollment-collection-widget.js
- Add a basic loading spinner that is reveals the widget when all sub-entities have loaded. This implementation does not wait until all images are loaded since their loading is handled by events rather than loading them as sub-entities. Image support will be added in the future as required.
> US112310: Give the My Learning widget a basic loading spinner

- components/d2l-enrollment-collection-view/d2l-enrollment-collection-view.js
- components/d2l-enrollment-collection-view/lang/en.js
- components/d2l-enrollment-collection-view/lang/fr.js
- components/d2l-enrollment-collection-view/localization.js
- polymer.json
small pr for fixing margin and added local
> fixed margin and add localization for my learning

- components/d2l-enrollment-collection-view/d2l-enrollment-collection-view.js
- components/d2l-enrollment-collection-view/lang/en.js
This pull request finalizes the My Learning page by adding:
- Load more paging
- Searching
- Loading spinners
- Responsiveness
- Localization
- Loading Skeletons
> My Learning Page

- components/d2l-enrollment-collection-view/d2l-enrollment-collection-view.js
- components/d2l-enrollment-collection-view/lang/en.js
- package.json
- test/d2l-enrollment-collection-view/d2l-enrollment-collection-view.html
- test/d2l-enrollment-collection-view/d2l-enrollment-collection-view.js
- test/index.html
- Add `aria-busy` attribute to the list component so its busy during initial load, searching, and load more
- Add focus on the first new item when load more is clicked.
- Add `axe-core` tests
> Accessibility Improvements

- components/d2l-enrollment-collection-view/d2l-enrollment-collection-view.js
> Update actions in my learning list items

- components/d2l-enrollment-collection-view/d2l-enrollment-collection-view.js
[DE37487](https://rally1.rallydev.com/#/detail/defect/362507044272?fdp=true)
Floating dot was appearing in the metadata for My Learning in cases where a course was partially completed. This was due to siren-sdk returning undefined instead of null.
The floating dot will no longer render in these cases.
> Fixed floating dot in My Learning metadata

- components/d2l-enrollment-collection-view/d2l-enrollment-collection-view.js
Depends on: https://git.dev.d2l/projects/CORE/repos/lms/pull-requests/7604/overview
> DE37457 - add support for excludeIndirect

- components/d2l-enrollment-collection-view/d2l-enrollment-collection-view.js
> use hasDate instead of hasDueDate

- components/d2l-enrollment-collection-view/d2l-enrollment-collection-view.js
context:
BrightspaceUI/core#681
This updates the slot name secondary so supporting-info
> Update slot name to supporting-info

- components/d2l-enrollment-card/d2l-enrollment-card.js
This is an HTML change, it doesn't affect how the data is displayed, but is found in the source HTML as a value.
> DE444450 - Convert the processedDate to the user's LMS set timezone
